//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 產生的 Include 檔案。
// 由 game.rc 使用
//
#define stage2_background               1
#define IDD_ABOUTBOX                    100
#define IDP_SOCKETS_INIT_FAILED         104
#define IDR_MAINFRAME                   128
#define IDR_GAMETYPE                    129
#define IDB_BALL                        130
#define IDB_RACKET                      131
#define IDB_ERASER1                     131
#define IDB_BITMAP1                     132
#define IDB_BACKGROUND                  132
#define IDB_CORNER                      133
#define IDB_BALL1                       134
#define IDB_BALL2                       135
#define IDB_BALL3                       136
#define IDB_BALL4                       137
#define IDB_0                           138
#define IDB_1                           139
#define IDB_2                           140
#define IDB_3                           141
#define IDB_4                           142
#define IDB_5                           143
#define IDB_6                           144
#define IDB_7                           145
#define IDB_8                           146
#define IDB_9                           147
#define IDB_MINUS                       148
#define IDB_CENTER                      149
#define IDB_ERASER2                     150
#define IDB_ERASER3                     151
#define IDB_CONTINUE                    152
#define IDC_GAMECURSOR                  153
#define IDB_HELP                        155
#define IDB_BITMAP2                     156
#define IDB_LOADING                     156
#define IDB_BITMAP4                     158
#define IDB_STAGE1_BG                   158
#define STAGE1_BG                       158
#define snake_right                     158
#define IDB_C_SL                        159
#define character_left_stand            159
#define IDB_C_WL                        160
#define character_left_walk1            160
#define IDB_C_WL2                       161
#define character_left_walk2            161
#define IDB_C_SR                        162
#define character_right_stand           162
#define IDB_C_WR                        163
#define character_right_walk1           163
#define IDB_C_WR2                       164
#define character_right_walk2           164
#define IDB_C_LIE                       168
#define character_right_jump            168
#define IDB_C_LL                        171
#define character_left_lie              171
#define IDC_CURSOR1                     174
#define IDB_C_LR                        175
#define character_right_lie             175
#define IDB_C_JL                        178
#define character_left_jump             178
#define IDB_C_JR                        179
#define IDB_S_L                         180
#define snail_left                      180
#define IDB_S_R                         181
#define snail_right                     181
#define IDB_SK_L                        182
#define snake_left                      182
#define IDB_SK_R                        183
#define IDB_C_C1                        184
#define character_climb1                184
#define IDB_C_C2                        185
#define character_climb2                185
#define IDB_C_AL1                       186
#define character_left_attack1_1        186
#define IDB_C_AL2                       188
#define IDB_C_AL3                       189
#define character_left_attack1_3        189
#define IDB_C_AL4                       190
#define character_left_attack2_1        190
#define IDB_C_AL5                       191
#define character_left_attack2_2        191
#define IDB_C_AL6                       192
#define character_left_attack3_1        192
#define IDB_C_AL7                       193
#define character_left_attack3_2        193
#define IDB_S_WL1                       194
#define snail_left_walk1                194
#define IDB_S_WL2                       195
#define snail_left_walk2                195
#define IDB_S_WL3                       196
#define snail_left_walk3                196
#define IDB_S_HL                        197
#define snail_left_hurt                 197
#define IDB_S_DL1                       198
#define snail_left_die1                 198
#define IDB_S_DL2                       199
#define snail_left_die2                 199
#define IDB_S_DL3                       200
#define snail_left_die3                 200
#define IDB_S_WR1                       201
#define snail_right_walk1               201
#define IDB_S_WR2                       202
#define snail_right_walk2               202
#define IDB_S_WR3                       203
#define snail_right_walk3               203
#define IDB_S_HR                        204
#define snail_right_hurt                204
#define IDB_S_DR1                       205
#define snail_right_die1                205
#define IDB_S_DR2                       206
#define snail_right_die2                206
#define IDB_BITMAP5                     207
#define IDB_S_DR3                       207
#define snail_right_die3                207
#define IDB_C_AR1                       208
#define character_right_attack1_1       208
#define IDB_C_AR2                       209
#define IDB_C_AR3                       210
#define character_right_attack1_3       210
#define IDB_C_AR4                       211
#define character_right_attack2_1       211
#define IDB_C_AR5                       212
#define character_right_attack2_2       212
#define IDB_C_AR6                       213
#define character_right_attack3_1       213
#define IDB_C_AR7                       214
#define character_right_attack3_2       214
#define IDB_BITMAP3                     216
#define IDB_STAGE2_BG                   216
#define stage1_background               216
#define character_left_attack1_2        218
#define character_right_attack1_2       219
#define stage3_background               220
#define menu_background                 221
#define start_button                    222
#define IDB_BITMAP6                     223
#define start_button2                   223
#define IDC_README                      1001
#define ID_FILE_PAUSE                   32771
#define ID_TOGGLE_FULLSCREEN            32772
#define ID_BUTTON_FULLSCREEN            32773
#define ID_BUTTON_PAUSE                 32774
#define ID_BUTTON_UNITTEST              32775

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        224
#define _APS_NEXT_COMMAND_VALUE         32776
#define _APS_NEXT_CONTROL_VALUE         1003
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
